sdf: arena_flat.sdf
spawn:
  loader: 0
  pose:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  velocity:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
water:
  sdf: arena_water.sdf
  height: 0.0
  velocity:
  - 0
  - 0
  - 0
  viscosity: 1.0
  maps:
  - ''
  - ''
ground_height: -1.0